### ISSUE TITLE
SystemError thrown when the player zooms out too far

### ISSUE THREAD

**Issue by ghost** [nathanwoodward/space_game#20]
steps to reproduce:
while true: zoom_out()

```Traceback (most recent call last):
  File "./run.py", line 23, in <module>
    main()
  File "./run.py", line 10, in main
    game.run()
  File "/home/user/big/src/space_game/src/game.py", line 223, in run
    self.run_update_loop()
  File "/home/user/big/src/space_game/src/game.py", line 164, in run_update_loop
    self.drawing.draw(self.camera.get_component(Camera))
  File "/home/user/big/src/space_game/src/drawing.py", line 110, in draw
    if not camera.check_bounds_world(drawable.estimate_bounds()):
  File "/home/user/big/src/space_game/src/behaviours.py", line 799, in check_bounds_world
    self_box.width /= self.__zoom
SystemError: error return without exception set```

**Comment by nathanrw** [comment]
dunno what that is but looks like division by zero?
